### ISSUE TITLE
Dok portalen videresender til prerelease versjon av dokumentasjon

### ISSUE THREAD

**Issue by eidjord** [FINTprosjektet/fint-informasjonsmodell-documentation#1]
Det er opprettet en ny release på fint-infoportalen github repo: https://github.com/FINTprosjektet/fint-informasjonsmodell/releases (`v1.1.0-rc1`). Den er markert som pre-release. Det finnes også tidligere release `v1.0.1` som er markert som en ekte release.
Jeg ser at når man går på hjemmesiden til dokumentasjonsportalen ( https://informasjonsmodell.felleskomponent.no/ ), blir man vidersendt til versjon `v1.1.0-rc1`. Det er feil så vidt jeg fortår dette, siden releasen `v1.1.0-rc1` er en prerelease. Vi trenger å sende brukerne til den siste ekte release (`v1.0.1` i dette tilfelle).

WS til github inneholder funksjonalitet for å finne `latest`, som gir siste versjon (og ser bort fra pre-release).

**Comment by OysteinAmundsen** [comment]
Now fetching https://api.github.com/repos/FINTprosjektet/fint-informasjonsmodell/releases/latest as the default selected version name.

Also using https://api.github.com/repos/FINTprosjektet/fint-informasjonsmodell/releases instead of https://api.github.com/repos/FINTprosjektet/fint-informasjonsmodell/tags for version list
